// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eMedicalRecords.Infrastructure;

namespace eMedicalRecords.Infrastructure.Migrations
{
    [DbContext(typeof(MedicalRecordContext))]
    partial class MedicalRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("_createdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("_updatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("mr_documents");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("_description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("_headingSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("heading_set_id");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("_templateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("_templateId");

                    b.ToTable("mr_entries");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.EntryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EntryId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("_entryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("_sectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("_value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntryId1");

                    b.HasIndex("_entryId");

                    b.HasIndex("_sectionId");

                    b.ToTable("mre_entry_data");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.PatientAggregate.IdentityType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("identity_type");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.PatientAggregate.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("IdentityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("_dateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("_firstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("_hasInsurance")
                        .HasColumnType("boolean")
                        .HasColumnName("has_insurance");

                    b.Property<string>("_identityNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_no");

                    b.Property<string>("_lastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("_middleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("_phoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("IdentityTypeId");

                    b.HasIndex("PatientNo")
                        .IsUnique();

                    b.HasIndex("_identityNo")
                        .IsUnique();

                    b.ToTable("patients");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("control_base_id");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("_sectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.HasKey("Id");

                    b.HasIndex("_sectionId");

                    b.ToTable("mre_control_base");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("control_types");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdditionalControlInformationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("_controlTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("control_type_id");

                    b.Property<string>("_description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<List<string>>("_options")
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<Guid?>("_parentSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_section_id");

                    b.Property<string>("_tooltip")
                        .HasColumnType("text")
                        .HasColumnName("tooltip");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalControlInformationId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("_controlTypeId");

                    b.HasIndex("_parentSectionId");

                    b.ToTable("mre_sections");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("_isDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("mre_template");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlText", b =>
                {
                    b.HasBaseType("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlBase");

                    b.Property<string>("_customExpression")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("custom_expression");

                    b.Property<int?>("_maximumLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("maximum_length");

                    b.Property<int?>("_minimumLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("minimum_length");

                    b.Property<int?>("_textRestrictionLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("text_restriction_level");

                    b.ToTable("mre_control_text");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Entry", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Document", null)
                        .WithMany("DocumentEntries")
                        .HasForeignKey("DocumentId");

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Template", null)
                        .WithMany()
                        .HasForeignKey("_templateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.EntryData", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Entry", null)
                        .WithMany("RecordValues")
                        .HasForeignKey("EntryId1");

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("_entryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", null)
                        .WithMany()
                        .HasForeignKey("_sectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.PatientAggregate.Patient", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.PatientAggregate.IdentityType", "IdentityType")
                        .WithMany()
                        .HasForeignKey("IdentityTypeId");

                    b.OwnsOne("eMedicalRecords.Domain.AggregatesModel.PatientAggregate.PatientAddress", "PatientAddress", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .HasColumnType("text");

                            b1.HasKey("PatientId");

                            b1.ToTable("patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("IdentityType");

                    b.Navigation("PatientAddress");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlBase", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", "Section")
                        .WithMany()
                        .HasForeignKey("_sectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlBase", "AdditionalControlInformation")
                        .WithMany()
                        .HasForeignKey("AdditionalControlInformationId");

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Template", null)
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId");

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlType", "ControlType")
                        .WithMany()
                        .HasForeignKey("_controlTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", null)
                        .WithMany("ChildSections")
                        .HasForeignKey("_parentSectionId");

                    b.Navigation("AdditionalControlInformation");

                    b.Navigation("ControlType");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlText", b =>
                {
                    b.HasOne("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlBase", null)
                        .WithOne()
                        .HasForeignKey("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.ControlText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Document", b =>
                {
                    b.Navigation("DocumentEntries");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.DocumentAggregate.Entry", b =>
                {
                    b.Navigation("RecordValues");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Section", b =>
                {
                    b.Navigation("ChildSections");
                });

            modelBuilder.Entity("eMedicalRecords.Domain.AggregatesModel.TemplateAggregate.Template", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
